"""first user and invoice migration

Revision ID: 8f3a4af039f0
Revises: 7a86f3963373
Create Date: 2023-10-11 16:58:34.965164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3a4af039f0'
down_revision = '7a86f3963373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
