
# Generated by CodiumAI
import app


import pytest

class TestRoot:

    # Returns a JSON object with a welcome message.
    @pytest.mark.asyncio
    async def test_returns_welcome_message(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert response.json() == {"message": "welcome to my invoicing app"}

